image: ubuntu

branches:
  only:
    - master

max_jobs: 2

environment:
   BOARD_ARCH: amd64
   CHROMEOS_STABILIZE_VERSION: stabilize-10718.88.B

install:
  - .ci/setup-env
  - source $HOME/.profile

# scripts to run before build
before_build:
  - cros_sdk -- ./setup_board --board=maru-$BOARD_ARCH
  - cros_sdk -- ./build_packages --board=maru-$BOARD_ARCH 
# to run your custom scripts instead of automatic MSBuild
build_script:
  - cros_sdk -- ./build_image --board=maru-$BOARD_ARCH
# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - ls build/chromiumos-*/src/build/images/maru-$BOARD_ARCH

build: on