trigger:
 - master

jobs:
- job: build_amd64
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    board_arch: amd64
    chromeos_stabilize_version: stabilize-10718.88.B
  steps:
    - bash: ./.ci/setup-env
    - bash: cros_sdk -- ./setup_board --board=maru-$(board_arch)
    - bash: cros_sdk -- ./build_packages --board=maru-$(board_arch)
    - bash: cros_sdk -- ./build_image --board=maru-$(board_arch)