trigger:
 - master

jobs:
- job: build_amd64
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    board_arch: amd64
    chromeos_stabilize_version: stabilize-10718.88.B
  steps:
    - bash: ./.ci/setup-env
    - bash: cd build/chromiumos-$(chromeos_stabilize_version)/src/build/images/maru-$(board_arch) && ls