version: 2
notify:
  webhooks:
    - url: https://circledisc-clarity.herokuapp.com/webhook/circle

jobs:
  build_amd64:
    machine: true
    environment:
      BOARD_ARCH: amd64
      CHROMEOS_STABILIZE_VERSION: release-R74-11895.B
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: .ci/setup-env         
      - run:
          name: Build Image
          command: .ci/build

  deploy_amd64:
    machine: true
    environment:
      BOARD_ARCH: amd64
      CHROMEOS_STABILIZE_VERSION: release-R74-11895.B
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: .ci/setup-env         
      - run:
          name: Build Image
          command: .ci/build
      - run:
          name: Publish to GitHub
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate ${CHROMEOS_STABILIZE_VERSION} ./artifacts/    



workflows:
  version: 2
  untagged-build:
    jobs:
      - build_amd64
  tagged-build:
    jobs:
      - deploy_amd64:
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            tags:
              only: /release-R[0-9]{2}-[0-9]{5}\.B/