version: 2
notify:
  webhooks:
    - url: https://circledisc-clarity.herokuapp.com/webhook/circle

jobs:
  prebuild_amd64:
    machine: true
    env:
      CHROMEOS_STABILIZE_VERSION: release-R75-12105.B 
      BOARD_ARCH: amd64
    steps:
      - checkout 
      - run:
         name: Checkout Chromium OS Source code
         command: .ci/setup-env
      - run:
          name: CROS_SDK -  Walk to CrOS directory and Setup Board
          command: |
            source $HOME/.profile;
            cp -vRf ./overlay-* build/chromiumos-$CHROMEOS_STABILIZE_VERSION/src/overlays/
            mkdir /tmp/crosbuild && cp -vRf build/chromiumos-$CHROMEOS_STABILIZE_VERSION/* /tmp/crosbuild
            cd /tmp/crosbuild
            cros_sdk --download -- setup_board --board=maru-$BOARD_ARCH;
      - run:
          name: Prepare passing to downstream
          command: chown -R $(id -u):0 /tmp/crosbuild/chroot
      - persist_to_workspace:
          root: /tmp
          paths:
            - crosbuild

  packagebuild_amd64:
    machine: true
    working_directory: /tmp 
    env:
      CHROMEOS_STABILIZE_VERSION: release-R75-12105.B 
      BOARD_ARCH: amd64
    steps:
      - attach_workspace:
          at: /tmp/crosbuild
      - run:
         name: Setup Environment
         command: wget -qO - https://git.io/Je3Q6 | sh
      - run:
          name: CROS_SDK -  Build Image
          command: |
            source $HOME/.profile;
            cros_sdk --download -- ./build_packages --board=maru-$BOARD_ARCH;
      - run:
          name: Prepare passing to downstream
          command: chown -R $(id -u):0 /tmp/crosbuild/chroot
      - persist_to_workspace:
          root: /tmp
          paths:
            - crosbuild

  postbuild_amd64:
    machine: true
    working_directory: /tmp 
    env:
      CHROMEOS_STABILIZE_VERSION: release-R75-12105.B 
      BOARD_ARCH: amd64
    steps:
      - attach_workspace:
          at: /tmp/crosbuild
      - run:
         name: Setup Environment
         command: wget -qO - https://git.io/Je3Q6 | sh
      - run:
          name: CROS_SDK -  Build Image
          command: |
            source $HOME/.profile;
            cros_sdk --download -- ./build_image --board=maru-$BOARD_ARCH;
      - run:
          name: Prepare passing to downstream
          command: chown -R $(id -u):0 /tmp/crosbuild/chroot
      - persist_to_workspace:
          root: /tmp
          paths:
            - crosbuild
  nightly_deploy_amd64:
    machine: true
    working_directory: /tmp 
    env:
      CHROMEOS_STABILIZE_VERSION: release-R75-12105.B 
      BOARD_ARCH: amd64
    steps:
      - attach_workspace:
          at: /tmp/crosbuild
      - run:
         name: Setup Environment
         command: wget -qO - https://git.io/Je3Q6 | sh
      - run:
          name: Package Image for distribution
          command: |
            source $HOME/.profile;
            tar -czvf $HOME/maru-image.tgz crosbuild/src/build/images/maru-$BOARD_ARCH

  deploy_amd64:
    machine: true
    working_directory: /tmp 
    env:
      CHROMEOS_STABILIZE_VERSION: release-R75-12105.B 
      BOARD_ARCH: amd64
    steps:
      - attach_workspace:
          at: /tmp/crosbuild
      - run:
         name: Setup Environment
         command: wget -qO - https://git.io/Je3Q6 | sh
      - run:
          name: Package Image for distribution
          command: |
            source $HOME/.profile;
            tar -czvf $HOME/maru-image.tgz crosbuild/src/build/images/maru-$BOARD_ARCH

workflows:
  version: 2
  untagged-build:
    jobs:
      - prebuild_amd64
      - packagebuild_amd64:
          requires: 
            - 'prebuild-amd64'
      - postbuild_amd64:
          requires:
            - 'packagebuild_amd64'
      - nightly_deploy_amd64:
          requires:
            - 'postbuild_amd64'

  tagged-build:
    jobs:
      - prebuild_amd64
      - packagebuild_amd64:
          requires: 
            - 'prebuild-amd64'
      - postbuild_amd64:
          requires:
            - 'packagebuild_amd64'
      - deploy_amd64:
          requires: 
            - 'postbuild-amd64'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release-R[0-9]{2}-[0-9]{5}\.B/
