#!/bin/sh
# Copyright 2019 (c) Kibo Hikari
# Licensed under MIT

echo 'target_os = ["chromeos"]' > $HOME/.gclient;

sudo mkdir -p /usr/local/repo
sudo chmod -R 777 /usr/local/repo
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /usr/local/repo/depot_tools
export PATH=/usr/local/repo/depot_tools:$PATH

umask 022

cp -vRf ../overlays/* src/overlays/;

wget -qO - https://gist.githubusercontent.com/sr229/b88ffa3427ded4a71580e62e442204e5/raw/b7664bb61390476a66f0ad9c4d6716010114cd80/.googleapikeys > $HOME/.googleapikeys

echo 'export PATH=/usr/local/repo/depot_tools:$PATH' >> $HOME/.profile;

mkdir -p build/chromium 

cd build/chromium && \
   fetch --nohooks --no-history chromium && \
   ./build/install-build-deps-android.sh && \
   ./build/install-build-deps.sh;

gclient runhooks;

## TODO: Run this non-interactively
cros chrome-sdk --board=$BOARD --log-level=info --download-vm --gn-extra-args='dcheck_always_on=true ';
