name: Build - Commit
on: 
  push:
    branches:
       - *

jobs:
  build:
    name: Build - amd64 Overlay
    runs-on: ubuntu-16.04
    env:
      chromeos_stabilize_version: release-R76-12239.B
      board_arch: amd64
    steps:
      - uses: actions/checkout@v1

      - name: Setup Environment
        run: .ci/setup-env

      - name: Build Image
        run: cp -vRf ./overlay-* build/chromiumos-$CHROMEOS_STABILIZE_VERSION/src/overlays/ && .ci/build
