name: Build - Commit
on: [push, pull_request]
jobs:
  preload:
     name: 'Preload Board Setup'
     runs-on: 'ubuntu-latest'
     steps:
       - uses: actions/checkout@master

       - name: Setup Environment
         run: .ci/setup-env
         env:
           CHROMEOS_STABILIZE_VERSION: release-R76-12239.B
           BOARD_ARCH: amd64

       - name: Setup Board
         run: |
           source $HOME/.profile
           cp -vRf ./overlay-* build/chromiumos-${CHROMEOS_STABILIZE_VERSION}/src/overlays/
           cd build/chromiumos-${CHROMEOS_STABILIZE_VERSION}/
           cros_sdk --download -- setup_board --board=maru-${BOARD_ARCH}
         env:
            CHROMEOS_STABILIZE_VERSION: release-R76-12239.B
            BOARD_ARCH: amd64
            
       - name: Workaround Permissions for chroots
         run: sudo chown -R $(id -u):0 build/chromiumos-${CHROMEOS_STABILIZE_VERSION}/chroot/
         env:
            CHROMEOS_STABILIZE_VERSION: release-R76-12239.B
            BOARD_ARCH: amd64

       - uses: actions/upload-artifact@master
         with:
           name: cros-build-data
           path: build/
  build:
    name: Build (AMD64)
    needs: preload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: cros-build-data

      - name: Setup Environment
        run: wget -qO - https://git.io/Je3Q6 | sh
      
      - name: Build Packages
        run: |
           source $HOME/.profile
           cd build/chromiumos-$CHROMEOS_STABILIZE_VERSION/
           cros_sdk --download -- ./build_packages --nowithdebug --board=maru-$BOARD_ARCH
        env:
           CHROMEOS_STABILIZE_VERSION: release-R76-12239.B
           BOARD_ARCH: amd64

      - uses: actions/upload-artifact@master
        with:
          name: cros-to-finalize
          path: build/

  finalize:
    name: Finalize (AMD64)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: cros-to-finalize

      - name: Setup Environment
        run: wget -qO - https://git.io/Je3Q6 | sh
      
      - name: Build Image
        run: |
           source $HOME/.profile
           cd build/chromiumos-$CHROMEOS_STABILIZE_VERSION/
           cros_sdk --download -- ./build_image --board=maru-$BOARD_ARCH
        env:
           CHROMEOS_STABILIZE_VERSION: release-R76-12239.B
           BOARD_ARCH: amd64