name: Build - Release
on: release

jobs:
  build:
    name: Setup Environment and Build Image
    runs-on: ubuntu-16.04
    env:
      chromeos_stabilize_version: release-R75-12105.B
      board_arch: amd64
    steps:
      - uses: actions/checkout@v1

      - name: Setup Environment
        run: .ci/setup-env

      - name: Build Image
        run: .ci/build

      # TODO: upload git artifact to Git tag.
      - name: Prepare Image for deployment
        run: tar -czvf $HOME/cros-$CHROMEOS_STABILIZE_VERSION.tar.gz build/chromiumos-$CHROMEOS_STABILIZE_VERSION/src/build/images/maru-amd64/latest/*.bin